In [1]:
import pandas as pd

In [7]:
df=pd.read_csv("SMSSpamCollection.txt", sep="\t", header=None, names=["label", "message"])

In [8]:
df.head()

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [9]:
#data cleaning and preprocessing
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ADMIN\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [11]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [14]:
corpus=[]
for i in range(0, len(df)):
    review=re.sub('[^a-zA-Z]', ' ' , df['message'][i])
    review=review.lower()
    review=review.split()
    review=[ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review=' '.join(review)
    corpus.append(review)

In [15]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

In [ ]:
#create bag of words model

from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=2500,binary=True)
X=cv.fit_transform(corpus).toarray()
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(5572, 2500))

(5572, 2500)

In [ ]:
# with lemmatization
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()
corp=[]
for i in range(0, len(df)):
    review=re.sub('[^a-zA-z]', ' ', df['message'][i])
    review=review.split()
    review=[lemmatizer.lemmatize(word) for word in review if not word in set(stopwords.words('english'))]
    review=" ".join(review)
    corp.append(review)


['Go jurong point crazy Available bugis n great world la e buffet Cine got amore wat',
 'Ok lar Joking wif u oni',
 'Free entry wkly comp win FA Cup final tkts st May Text FA receive entry question std txt rate T C apply',
 'U dun say early hor U c already say',
 'Nah I think go usf life around though',
 'FreeMsg Hey darling week word back I like fun still Tb ok XxX std chgs send rcv',
 'Even brother like speak They treat like aid patent',
 'As per request Melle Melle Oru Minnaminunginte Nurungu Vettam set callertune Callers Press copy friend Callertune',
 'WINNER As valued network customer selected receivea prize reward To claim call Claim code KL Valid hour',
 'Had mobile month U R entitled Update latest colour mobile camera Free Call The Mobile Update Co FREE',
 'I gonna home soon want talk stuff anymore tonight k I cried enough today',
 'SIX chance win CASH From pound txt CSH send Cost p day day TsandCs apply Reply HL info',
 'URGENT You week FREE membership Prize Jackpot Txt word 

In [38]:
corp

['Go jurong point crazy Available bugis n great world la e buffet Cine got amore wat',
 'Ok lar Joking wif u oni',
 'Free entry wkly comp win FA Cup final tkts st May Text FA receive entry question std txt rate T C apply',
 'U dun say early hor U c already say',
 'Nah I think go usf life around though',
 'FreeMsg Hey darling week word back I like fun still Tb ok XxX std chgs send rcv',
 'Even brother like speak They treat like aid patent',
 'As per request Melle Melle Oru Minnaminunginte Nurungu Vettam set callertune Callers Press copy friend Callertune',
 'WINNER As valued network customer selected receivea prize reward To claim call Claim code KL Valid hour',
 'Had mobile month U R entitled Update latest colour mobile camera Free Call The Mobile Update Co FREE',
 'I gonna home soon want talk stuff anymore tonight k I cried enough today',
 'SIX chance win CASH From pound txt CSH send Cost p day day TsandCs apply Reply HL info',
 'URGENT You week FREE membership Prize Jackpot Txt word 

In [36]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=2500, binary=True)
Y=cv.fit_transform(corp).toarray()
Y

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(5572, 2500))

In [41]:
# N-grams on BOW

cv.vocabulary_

{'go': np.int64(851),
 'point': np.int64(1605),
 'crazy': np.int64(475),
 'available': np.int64(146),
 'bugis': np.int64(285),
 'great': np.int64(875),
 'world': np.int64(2443),
 'la': np.int64(1133),
 'cine': np.int64(393),
 'got': np.int64(866),
 'wat': np.int64(2358),
 'ok': np.int64(1479),
 'lar': np.int64(1143),
 'joking': np.int64(1093),
 'wif': np.int64(2403),
 'oni': np.int64(1489),
 'free': np.int64(785),
 'entry': np.int64(647),
 'wkly': np.int64(2428),
 'comp': np.int64(431),
 'win': np.int64(2408),
 'cup': np.int64(489),
 'final': np.int64(735),
 'tkts': np.int64(2181),
 'st': np.int64(2000),
 'may': np.int64(1292),
 'text': np.int64(2128),
 'receive': np.int64(1718),
 'question': np.int64(1675),
 'std': np.int64(2016),
 'txt': np.int64(2245),
 'rate': np.int64(1697),
 'apply': np.int64(101),
 'dun': np.int64(605),
 'say': np.int64(1816),
 'early': np.int64(611),
 'already': np.int64(65),
 'nah': np.int64(1409),
 'think': np.int64(2151),
 'usf': np.int64(2292),
 'life': np.

In [57]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=100,binary=True,ngram_range=(2,2))
X=cv.fit_transform(corpus).toarray()
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(5572, 100))

In [58]:
cv.vocabulary_

{'free entri': np.int64(33),
 'claim call': np.int64(16),
 'call claim': np.int64(3),
 'free call': np.int64(32),
 'chanc win': np.int64(15),
 'txt word': np.int64(88),
 'let know': np.int64(54),
 'go home': np.int64(37),
 'pleas call': np.int64(67),
 'lt gt': np.int64(58),
 'want go': np.int64(97),
 'first time': np.int64(31),
 'like lt': np.int64(55),
 'sorri call': np.int64(80),
 'call later': np.int64(8),
 'ur award': np.int64(90),
 'call custom': np.int64(4),
 'custom servic': np.int64(23),
 'cash prize': np.int64(14),
 'po box': np.int64(68),
 'tri contact': np.int64(85),
 'draw show': np.int64(28),
 'show prize': np.int64(79),
 'prize guarante': np.int64(73),
 'guarante call': np.int64(44),
 'valid hr': np.int64(95),
 'select receiv': np.int64(76),
 'privat account': np.int64(71),
 'account statement': np.int64(0),
 'statement show': np.int64(81),
 'call identifi': np.int64(5),
 'identifi code': np.int64(50),
 'code expir': np.int64(20),
 'urgent mobil': np.int64(94),
 'call lan