In [1]:
import pandas as pd
df=pd.read_csv("SMSSpamCollection.txt", sep="\t", header=None, names=["label", "message"])

In [2]:
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ADMIN\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [4]:
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
lemmatizer = WordNetLemmatizer()
corp=[]
for i in range(0, len(df)):
    review=re.sub('[^a-zA-z]', ' ', df['message'][i])
    review=review.split()
    review=[lemmatizer.lemmatize(word) for word in review if not word in set(stopwords.words('english'))]
    review=" ".join(review)
    corp.append(review)

In [8]:
corp

['Go jurong point crazy Available bugis n great world la e buffet Cine got amore wat',
 'Ok lar Joking wif u oni',
 'Free entry wkly comp win FA Cup final tkts st May Text FA receive entry question std txt rate T C apply',
 'U dun say early hor U c already say',
 'Nah I think go usf life around though',
 'FreeMsg Hey darling week word back I like fun still Tb ok XxX std chgs send rcv',
 'Even brother like speak They treat like aid patent',
 'As per request Melle Melle Oru Minnaminunginte Nurungu Vettam set callertune Callers Press copy friend Callertune',
 'WINNER As valued network customer selected receivea prize reward To claim call Claim code KL Valid hour',
 'Had mobile month U R entitled Update latest colour mobile camera Free Call The Mobile Update Co FREE',
 'I gonna home soon want talk stuff anymore tonight k I cried enough today',
 'SIX chance win CASH From pound txt CSH send Cost p day day TsandCs apply Reply HL info',
 'URGENT You week FREE membership Prize Jackpot Txt word 

In [9]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=2500, binary=True)
Y=cv.fit_transform(corp).toarray()
Y

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(5572, 2500))

In [10]:
cv.vocabulary_

{'go': np.int64(851),
 'point': np.int64(1605),
 'crazy': np.int64(475),
 'available': np.int64(146),
 'bugis': np.int64(285),
 'great': np.int64(875),
 'world': np.int64(2443),
 'la': np.int64(1133),
 'cine': np.int64(393),
 'got': np.int64(866),
 'wat': np.int64(2358),
 'ok': np.int64(1479),
 'lar': np.int64(1143),
 'joking': np.int64(1093),
 'wif': np.int64(2403),
 'oni': np.int64(1489),
 'free': np.int64(785),
 'entry': np.int64(647),
 'wkly': np.int64(2428),
 'comp': np.int64(431),
 'win': np.int64(2408),
 'cup': np.int64(489),
 'final': np.int64(735),
 'tkts': np.int64(2181),
 'st': np.int64(2000),
 'may': np.int64(1292),
 'text': np.int64(2128),
 'receive': np.int64(1718),
 'question': np.int64(1675),
 'std': np.int64(2016),
 'txt': np.int64(2245),
 'rate': np.int64(1697),
 'apply': np.int64(101),
 'dun': np.int64(605),
 'say': np.int64(1816),
 'early': np.int64(611),
 'already': np.int64(65),
 'nah': np.int64(1409),
 'think': np.int64(2151),
 'usf': np.int64(2292),
 'life': np.

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [16]:
tfidf=TfidfVectorizer(max_features=100, binary=True)
X=tfidf.fit_transform(corp).toarray()
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(5572, 100))

In [21]:
import numpy as np
np.set_printoptions(edgeitems=30, linewidth=100000, formatter=dict(float=lambda x: "%.3g" % x))

In [22]:
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.434, 0, 0, 0.461, 0.544, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.55, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.556, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0.576, 0, 0, 0, 0, 0, 0, 0, 0, 0.599, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0.724, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.645, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.764, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [24]:
tfidf=TfidfVectorizer(max_features=100, ngram_range=(2, 2), binary=True)
X=tfidf.fit_transform(corp).toarray()
tfidf.vocabulary_

{'free entry': np.int64(30),
 'to claim': np.int64(81),
 'claim call': np.int64(15),
 'call claim': np.int64(3),
 'free call': np.int64(29),
 'chance win': np.int64(14),
 'txt word': np.int64(85),
 'let know': np.int64(51),
 'please call': np.int64(63),
 'lt gt': np.int64(55),
 'want go': np.int64(92),
 'like lt': np.int64(52),
 'sorry call': np.int64(74),
 'call later': np.int64(8),
 'ur awarded': np.int64(86),
 'how much': np.int64(46),
 'call customer': np.int64(4),
 'customer service': np.int64(22),
 'cash prize': np.int64(13),
 'po box': np.int64(65),
 'we trying': np.int64(94),
 'trying contact': np.int64(82),
 'draw show': np.int64(27),
 'show prize': np.int64(73),
 'prize guaranteed': np.int64(68),
 'guaranteed call': np.int64(38),
 'valid hr': np.int64(90),
 'selected receive': np.int64(70),
 'private your': np.int64(67),
 'your account': np.int64(98),
 'account statement': np.int64(0),
 'statement show': np.int64(75),
 'call identifier': np.int64(5),
 'identifier code': np.in